### PR TITLE
Simplified Installation Instructions

### PR DESCRIPTION
**Pull request by LeviBroadnax**
* Updated the readme to point at the LTS version of BepinEXv5 
* Added an installation script `install.ps1` for Windows machines

### CODE REVIEW

**Comment by pizzav-xyz** [comment]
What about proton for Linux?

**Comment by LeviBroadnax** [comment]
> What about proton for Linux?

Are you using a Steam Deck? The steps should be identical except with [BepInEx_linux_x64_5.4.23.2.zip](https://github.com/BepInEx/BepInEx/releases/download/v5.4.23.2/BepInEx_linux_x64_5.4.23.2.zip) as the BepinEx zip

**Comment by pizzav-xyz** [comment]
> > What about proton for Linux?
> 
> Are you using a Steam Deck? The steps should be identical except with [BepInEx_linux_x64_5.4.23.2.zip](https://github.com/BepInEx/BepInEx/releases/download/v5.4.23.2/BepInEx_linux_x64_5.4.23.2.zip) as the BepinEx zip

arch

**Comment by Swagguy47** [comment]
very good work!

**Pull request merged**
